sudo: required

language: sh

services:
  - docker

before_install:
  - echo "before_install()"
  - docker pull debian:jessie
  - cd jessie-ghc-7.10.3 && docker build .
  - docker ps -a

install:
  - echo "install()"

before_script:
  - echo "before_script()"

script:
  - echo "script()"
  - echo "----------------------------------------"
  - echo "----------------------------------------"
  - echo "----------------------------------------"
  - cat build.sh
  - cat /home/travis/build.sh
  - pwd
  - echo "----------------------------------------"
  - echo "----------------------------------------"
  - echo "----------------------------------------"
