sudo: false

language: sh

services:
  - docker

before_install:
  - echo before_install()
  - docker pull debian:jessie
  - docker build
  - docker ps -a

install:
  - echo install()

before_script:
  - echo before_script()

script:
  - echo script()
