#!/usr/bin/env bash

set -eu

cat /etc/apt/sources.list
echo 'deb http://httpredir.debian.org/debian jessie-backports main' >>/etc/apt/sources.list
apt-get update
apt-get -t jessie-backports install -y \
    ghc \
    cabal-install \
    git \
    make \
    pkg-config \
    zlib1g-dev \
    libffi-dev
ghc --version
cabal --version
git --version
pkg-config --version
