#!/usr/bin/bash

set -eu

cat /etc/apt/sources.list
echo 'deb http://httpredir.debian.org/debian jessie-backports main' >>/etc/apt/sources.list
apt-get update
apt-get -t jessie-backports install -y ghc cabal-install git
ghc --version
cabal --version
git --version
